apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: chat-app
type: Opaque
stringData:
  jwt-secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc4NTUyNTg0OSwiaWF0IjoxNzg1NTI1ODQ5fQ.YBSuZ4Cq3bRNgO_S9QPvPUmlcGDXHO49ZPTEyECp1So
"